### ISSUE TITLE
shape mismatch error when running the training file

### ISSUE THREAD

**Issue by Nadoay** [JihuaPeng/KTPFormer#19]
Hello! I am running a training process using the commands from the readme file, but I encountered an error during execution. The error message indicates there is a shape mismatch issue, and I'm unsure how to resolve it. The error details are as follows:：

```
Traceback (most recent call last):
  File "run_ktpformer.py", line 401, in <module>
    predicted_3d_pos = model_pos_train(inputs_2d)
  File "D:\ZYD\KTPFormer-main (2)\KTPFormer-main\common\model_ktpformer.py", line 634, in forward
    x = self.KPA_forward(x)
  File "D:\ZYD\KTPFormer-main (2)\KTPFormer-main\common\model_ktpformer.py", line 584, in KPA_forward
    x = rearrange(x, '(b f) n cw -> (b n) f cw', f=f)
einops.EinopsError:  Error while processing rearrange-reduction pattern "(b f) n cw -> (b n) f cw".
 Input tensor shape: torch.Size([1, 17, 512]). Additional info: {'f': 243}.
 Shape mismatch, can't divide axis of length 1 in chunks of 243
```

I am seeking guidance on how to address this issue and would be very grateful for any assistance you can provide!

**Comment by ek1den2** [comment]
Hello!
What dataset are you using for training?

**Comment by Nadoay** [comment]
> 你好！ 你使用什么数据集进行训练？

I have resolved the issue, Thank you for your reply！

**Comment by siyu-lii** [comment]
Hi, I'm having the same problem as you with training, the dataset I'm using is human3.6,can you please tell me how did you solve this problem? The error details are as follows:


Traceback (most recent call last):
  File "C:\Users\ps\.conda\envs\pytorch\lib\site-packages\torch\nn\parallel\parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "C:\Users\ps\.conda\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\lisiyu\KTPFormer-main\common\model_ktpformer.py", line 636, in forward
    x = self.KPA_forward(x)
  File "D:\lisiyu\KTPFormer-main\common\model_ktpformer.py", line 586, in KPA_forward
    x = rearrange(x, '(b f) n cw -> (b n) f cw', f=f)
  File "C:\Users\ps\.conda\envs\pytorch\lib\site-packages\einops\einops.py", line 483, in rearrange
    return reduce(cast(Tensor, tensor), pattern, reduction='rearrange', **axes_lengths)
  File "C:\Users\ps\.conda\envs\pytorch\lib\site-packages\einops\einops.py", line 420, in reduce
    raise EinopsError(message + '\n {}'.format(e))
einops.EinopsError:  Error while processing rearrange-reduction pattern "(b f) n cw -> (b n) f cw".
 Input tensor shape: torch.Size([1, 17, 512]). Additional info: {'f': 243}.
 Shape mismatch, can't divide axis of length 1 in chunks of 243
