### ISSUE TITLE
train 

### ISSUE THREAD

**Issue by zhimingzhu** [JihuaPeng/KTPFormer#23]
Traceback (most recent call last):
  File "run_ktpformer.py", line 429, in <module>
    loss_total.backward(loss_total.clone().detach())
  File "/root/miniconda3/lib/python3.8/site-packages/torch/_tensor.py", line 363, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/autograd/__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [1944, 17, 512]], which is output 0 of ReluBackward0, is at version 1; expected version 0 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).

Hello, I have encountered the above error in my training, is this problem due to configuration or is there any other reason?

**Comment by cdzzzz** [comment]
I encountered the same errors, have you solved it？

**Comment by yuhao-beep** [comment]
I encountered the same errors, have you solved it？

**Comment by rabbitchenrui** [comment]
It's a question in class KPA , there is a x = self.relu(x) which gradient get error....

**Comment by rabbitchenrui** [comment]
![image](https://github.com/user-attachments/assets/a4307664-0577-44a2-9b2c-2560dc0c46f7)
here I do not know why, but delete or replace this self.relu to nn.GELU it works, but you need retrain whole network

**Comment by zdpyz** [comment]
@rabbitchenrui    Excuse me.If the activation function is not changed, are there any other solutions?
